### ISSUE TITLE
Broken link on blog

### ISSUE THREAD

**Issue by eMan-2000** [benmayer/ben-mayer-nuxt-firebase#1]
In your nuxt-ssr-firebase-template, you link to this page: https://ben-mayer.com/blog/a-blog-built-using-nuxtjs-and-firebase/

Entering the site through that link prevents the page from loading, displaying: 

```
DOMException: Failed to execute 'appendChild' on 'Node': This node type does not support this method.
    at Object.appendChild (https://ben-mayer.com/_nuxt/583a379.js:2:41273)
    at m (https://ben-mayer.com/_nuxt/583a379.js:2:54196)
    at v (https://ben-mayer.com/_nuxt/583a379.js:2:53827)
    at _ (https://ben-mayer.com/_nuxt/583a379.js:2:54282)
    at M (https://ben-mayer.com/_nuxt/583a379.js:2:57668)
    at f.__patch__ (https://ben-mayer.com/_nuxt/583a379.js:2:58080)
    at f.t._update (https://ben-mayer.com/_nuxt/583a379.js:2:35019)
    at f.r (https://ben-mayer.com/_nuxt/583a379.js:2:65483)
    at _n.get (https://ben-mayer.com/_nuxt/583a379.js:2:27195)
    at new _n (https://ben-mayer.com/_nuxt/583a379.js:2:27113)
```

Tested in chrome. 

It seems the issue is with entering the site through that page, as if you navigate to that page directly from the main page of your blog, it doesn't cause any problems. Similarly, if you get the error by loading that page, and then try to navigate elsewhere from that page, it also causes issues. 

My guess is the issue is caused when the page is built server-side but doesn't have an issue when built client side (https://nuxtjs.org/docs/2.x/concepts/server-side-rendering/#server-side-rendering-steps-with-nuxtjs).

Otherwise, nice tutorial, thanks - testing it now, and hoping this issue isn't a general one that will affect my build!

**Comment by eMan-2000** [comment]
I think I found the issue: the link on your reddit post works, but not one the in github - the only difference is the latter has a trailing slash.
